#!/bin/bash
set -Eeuo pipefail

if [[ ${EUID} -ne 0 ]]; then
    printf 'Run this installer with sudo from an authenticated Plntir administrator session.\n' >&2
    exit 1
fi
if [[ $(/usr/bin/uname -s) != Darwin ]]; then
    printf 'This installer only supports macOS.\n' >&2
    exit 69
fi

PACKAGE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
readonly PACKAGE_DIR
readonly DEPLOYMENT_FILE=${PACKAGE_DIR}/deployment.conf
readonly PLNTIR_SHARED_ROOT=/Users/Shared/.plntir
readonly RESULT_ROOT=${PLNTIR_SHARED_ROOT}/results
readonly RESULT_DIR=${RESULT_ROOT}/access-upgrade
readonly STATUS_FILE=${RESULT_DIR}/status.json
readonly LOG_FILE=${RESULT_DIR}/install.log

write_status() {
    local state=$1
    local stage=$2
    local rc=$3
    local now tmp
    now=$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)
    tmp=${STATUS_FILE}.$$
    /usr/bin/printf '{"state":"%s","stage":"%s","rc":%d,"updated_at":"%s"}\n' \
        "${state}" "${stage}" "${rc}" "${now}" >"${tmp}"
    /bin/chmod 0644 "${tmp}"
    /bin/mv -f "${tmp}" "${STATUS_FILE}"
}

for directory in "${PLNTIR_SHARED_ROOT}" "${RESULT_ROOT}"; do
    if [[ -L ${directory} || (-e ${directory} && ! -d ${directory}) ]]; then
        printf 'Unsafe Plntir result parent: %s\n' "${directory}" >&2
        exit 77
    fi
    if [[ ! -e ${directory} ]]; then
        /bin/mkdir -m 0755 "${directory}"
    fi
    /usr/sbin/chown root:wheel "${directory}"
    /bin/chmod 0755 "${directory}"
    /usr/bin/chflags hidden "${directory}" 2>/dev/null || true
done
if [[ -L ${RESULT_DIR} || (-e ${RESULT_DIR} && ! -d ${RESULT_DIR}) ]]; then
    printf 'Unsafe result path: %s\n' "${RESULT_DIR}" >&2
    exit 77
fi
if [[ ! -e ${RESULT_DIR} ]]; then
    /bin/mkdir -m 0755 "${RESULT_DIR}"
fi
if [[ $(/usr/bin/stat -f %Su "${RESULT_DIR}") != root ]]; then
    printf 'Result directory must be owned by root.\n' >&2
    exit 77
fi
if [[ -n $(/usr/bin/find "${RESULT_DIR}" -maxdepth 0 \( -perm -020 -o -perm -002 \) -print -quit) ]]; then
    printf 'Result directory must not be group/other-writable.\n' >&2
    exit 77
fi
if [[ -L ${LOG_FILE} || -L ${STATUS_FILE} ]]; then
    printf 'Refusing unsafe result-file symlink.\n' >&2
    exit 77
fi
/usr/bin/touch "${LOG_FILE}"
/bin/chmod 0644 "${LOG_FILE}"
exec > >(/usr/bin/tee -a "${LOG_FILE}") 2>&1

stage=bootstrap
finished=false
on_exit() {
    local rc=$?
    trap - EXIT
    if [[ ${finished} == true && ${rc} -eq 0 ]]; then
        write_status success complete 0
        printf 'Plntir Secure Access Upgrade completed successfully.\n'
    else
        write_status failed "${stage}" "${rc}"
        printf 'Plntir Secure Access Upgrade failed during %s (rc=%d).\n' "${stage}" "${rc}" >&2
    fi
    exit "${rc}"
}
trap on_exit EXIT
write_status running "${stage}" 0

if [[ $(/usr/bin/stat -f %Su "${PACKAGE_DIR}") != root ]]; then
    printf 'Package must be copied into a root-owned staging directory first.\n' >&2
    exit 77
fi
unsafe_path=$(/usr/bin/find "${PACKAGE_DIR}" \( -perm -020 -o -perm -002 \) -print -quit)
if [[ -n ${unsafe_path} ]]; then
    printf 'Package contains a group/other-writable path: %s\n' "${unsafe_path}" >&2
    exit 77
fi
if [[ ! -f ${DEPLOYMENT_FILE} || -L ${DEPLOYMENT_FILE} ]]; then
    printf 'Deployment configuration is missing or unsafe.\n' >&2
    exit 66
fi

# generated by build-plntir-access-upgrade.sh and protected by the checked archive.
# shellcheck source=/dev/null
source "${DEPLOYMENT_FILE}"
: "${AGENT_USER:?}"
: "${BREAKGLASS_USER:?}"
: "${PLNTIR_CONTROL_NODE_IP:?}"
readonly AGENT_USER BREAKGLASS_USER PLNTIR_CONTROL_NODE_IP
for account in "${AGENT_USER}" "${BREAKGLASS_USER}"; do
    [[ ${account} =~ ^[A-Za-z0-9._-]+$ && ! ${account} == -* ]] || exit 64
done
[[ ${PLNTIR_CONTROL_NODE_IP} =~ ^[A-Fa-f0-9:.]+$ ]] || exit 64

# nested packages are extracted below a root-only temporary directory. switch
# to a traversable working directory before any command runs as macagent.
cd /

stage=preflight
write_status running "${stage}" 0
console_user=$(/usr/bin/stat -f %Su /dev/console)
case ${console_user} in
root | loginwindow | _mbsetupuser | '')
    printf 'No authenticated console user is active.\n' >&2
    exit 77
    ;;
esac
/usr/bin/id "${AGENT_USER}" >/dev/null
/usr/bin/id "${BREAKGLASS_USER}" >/dev/null
printf 'Authenticated-console preflight passed for %s on macOS %s.\n' \
    "${console_user}" "$(/usr/bin/sw_vers -productVersion)"

stage=provisioning
write_status running "${stage}" 0
"${PACKAGE_DIR}/scripts/provision-plntir-access-upgrade.sh" \
    "${PACKAGE_DIR}" \
    "${AGENT_USER}" \
    "${BREAKGLASS_USER}" \
    "${PLNTIR_CONTROL_NODE_IP}" \
    "${PACKAGE_DIR}/keys/archive.pub" \
    "${PACKAGE_DIR}/keys/breakglass.pub"

stage=verification
write_status running "${stage}" 0
"${PACKAGE_DIR}/scripts/verify-plntir-access-upgrade.sh" \
    "${AGENT_USER}" \
    "${BREAKGLASS_USER}" \
    "${PLNTIR_CONTROL_NODE_IP}" \
    "${PACKAGE_DIR}/keys/archive.pub" \
    "${PACKAGE_DIR}/keys/breakglass.pub"

printf 'Private user data was not scanned during this installation.\n'
printf 'macOS privacy permissions remain unchanged; private-data access stays on-demand.\n'
finished=true
