#!/bin/bash
set -Eeuo pipefail

if [[ ${EUID} -ne 0 ]]; then
    printf 'Run this installer with sudo from the physical Mac session.\n' >&2
    exit 1
fi
if [[ $(/usr/bin/uname -s) != Darwin ]]; then
    printf 'This installer only supports macOS.\n' >&2
    exit 69
fi

PACKAGE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
readonly PACKAGE_DIR
readonly DEPLOYMENT_FILE=${PACKAGE_DIR}/deployment.conf
readonly SYSTEM_KEYCHAIN=/Library/Keychains/System.keychain
readonly PLNTIR_SHARED_ROOT=/Users/Shared/.plntir
readonly RESULT_ROOT=${PLNTIR_SHARED_ROOT}/results
readonly RESULT_DIR=${RESULT_ROOT}/cloudflare-ca-trust
readonly STATUS_FILE=${RESULT_DIR}/status.json
readonly LOG_FILE=${RESULT_DIR}/install.log
readonly TLS_FILE=${RESULT_DIR}/tls-probe.txt

trusted=false
inspection_observed=false
stage=bootstrap
finished=false
trust_changed=false
cert_present_before=false

write_status() {
    local state=$1
    local current_stage=$2
    local rc=$3
    local now tmp
    now=$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)
    tmp=${STATUS_FILE}.$$
    /usr/bin/printf '{"state":"%s","stage":"%s","rc":%d,"trusted_for_tls":%s,"tls_inspection_observed":%s,"updated_at":"%s"}\n' \
        "${state}" "${current_stage}" "${rc}" "${trusted}" "${inspection_observed}" "${now}" >"${tmp}"
    /bin/chmod 0644 "${tmp}"
    /bin/mv -f "${tmp}" "${STATUS_FILE}"
}

for directory in "${PLNTIR_SHARED_ROOT}" "${RESULT_ROOT}"; do
    if [[ -L ${directory} || (-e ${directory} && ! -d ${directory}) ]]; then
        printf 'Unsafe Plntir result parent: %s\n' "${directory}" >&2
        exit 77
    fi
    if [[ ! -e ${directory} ]]; then
        /bin/mkdir -m 0755 "${directory}"
    fi
    /usr/sbin/chown root:wheel "${directory}"
    /bin/chmod 0755 "${directory}"
    /usr/bin/chflags hidden "${directory}" 2>/dev/null || true
done
if [[ -L ${RESULT_DIR} || (-e ${RESULT_DIR} && ! -d ${RESULT_DIR}) ]]; then
    printf 'Unsafe result path: %s\n' "${RESULT_DIR}" >&2
    exit 77
fi
if [[ ! -e ${RESULT_DIR} ]]; then
    /bin/mkdir -m 0755 "${RESULT_DIR}"
fi
if [[ $(/usr/bin/stat -f %Su "${RESULT_DIR}") != root ]]; then
    printf 'Result directory must be owned by root.\n' >&2
    exit 77
fi
if [[ -n $(/usr/bin/find "${RESULT_DIR}" -maxdepth 0 \( -perm -020 -o -perm -002 \) -print -quit) ]]; then
    printf 'Result directory must not be group/other-writable.\n' >&2
    exit 77
fi
if [[ -L ${LOG_FILE} || -L ${STATUS_FILE} || -L ${TLS_FILE} ]]; then
    printf 'Refusing unsafe result-file symlink.\n' >&2
    exit 77
fi
/usr/bin/touch "${LOG_FILE}"
/bin/chmod 0644 "${LOG_FILE}"
exec > >(/usr/bin/tee -a "${LOG_FILE}") 2>&1

system_has_pinned_cert() {
    local listing
    listing=$(/usr/bin/security find-certificate \
        -a -c "${EXPECTED_COMMON_NAME}" -Z "${SYSTEM_KEYCHAIN}" 2>/dev/null || true)
    /usr/bin/awk -v expected="${EXPECTED_SHA256}" \
        '$0 == "SHA-256 hash: " expected {found=1} END {exit(found ? 0 : 1)}' \
        <<<"${listing}"
}

admin_trust_has_expected_ca() {
    local settings
    settings=$(/usr/bin/security dump-trust-settings -d 2>/dev/null || true)
    /usr/bin/awk -v expected="${EXPECTED_COMMON_NAME}" \
        'index($0, expected) {found=1} END {exit(found ? 0 : 1)}' \
        <<<"${settings}"
}

rollback_trust() {
    set +e
    /usr/bin/security remove-trusted-cert -d "${SOURCE_CERT}" >/dev/null 2>&1
    if [[ ${cert_present_before} == true ]] && ! system_has_pinned_cert; then
        /usr/bin/security add-certificates -k "${SYSTEM_KEYCHAIN}" "${SOURCE_CERT}" >/dev/null 2>&1
    fi
    set -e
}

on_exit() {
    local rc=$?
    local failed_stage=${stage}
    trap - EXIT
    if [[ ${finished} == true && ${rc} -eq 0 ]]; then
        write_status success complete 0
        printf 'Cloudflare Gateway CA is trusted for TLS.\n'
    else
        if [[ ${trust_changed} == true ]]; then
            printf 'Verification failed; removing the newly added trust setting.\n' >&2
            rollback_trust
        fi
        trusted=false
        write_status failed "${failed_stage}" "${rc}"
        printf 'Cloudflare Gateway CA trust failed during %s (rc=%d).\n' "${failed_stage}" "${rc}" >&2
    fi
    exit "${rc}"
}
trap on_exit EXIT
write_status running "${stage}" 0

if [[ $(/usr/bin/stat -f %Su "${PACKAGE_DIR}") != root ]]; then
    printf 'Package must be in the root-owned staging directory.\n' >&2
    exit 77
fi
unsafe_path=$(/usr/bin/find "${PACKAGE_DIR}" \( -perm -020 -o -perm -002 \) -print -quit)
if [[ -n ${unsafe_path} ]]; then
    printf 'Package contains a group/other-writable path: %s\n' "${unsafe_path}" >&2
    exit 77
fi
if [[ ! -f ${DEPLOYMENT_FILE} || -L ${DEPLOYMENT_FILE} ]]; then
    printf 'Deployment configuration is missing or unsafe.\n' >&2
    exit 66
fi

# generated by the package builder and protected by the runner's pinned archive hash.
# shellcheck source=/dev/null
source "${DEPLOYMENT_FILE}"
: "${SOURCE_CERT:?}"
: "${EXPECTED_SHA256:?}"
: "${EXPECTED_COMMON_NAME:?}"
readonly SOURCE_CERT EXPECTED_SHA256 EXPECTED_COMMON_NAME

case ${SOURCE_CERT} in
/Library/Application\ Support/Cloudflare/installed_certs/*.pem) ;;
*)
    printf 'Refusing a certificate outside the Cloudflare installed-certs directory.\n' >&2
    exit 64
    ;;
esac
cert_basename=${SOURCE_CERT##*/}
[[ ${cert_basename} =~ ^[0-9A-Fa-f-]+\.pem$ ]] || exit 64
[[ ${EXPECTED_SHA256} =~ ^[0-9A-F]{64}$ ]] || exit 64
[[ ${EXPECTED_COMMON_NAME} == 'Gateway CA - Cloudflare Managed G1 '* ]] || exit 64
common_name_id=${EXPECTED_COMMON_NAME##* }
[[ ${common_name_id} =~ ^[0-9A-Fa-f]{32}$ ]] || exit 64

stage=certificate-preflight
write_status running "${stage}" 0
if [[ ! -f ${SOURCE_CERT} || -L ${SOURCE_CERT} ]]; then
    printf 'Cloudflare certificate is missing or is a symlink: %s\n' "${SOURCE_CERT}" >&2
    exit 66
fi
cert_parent=$(cd "$(dirname "${SOURCE_CERT}")" && pwd -P)
if [[ ${cert_parent} != '/Library/Application Support/Cloudflare/installed_certs' ]]; then
    printf 'Cloudflare certificate parent resolves to an unexpected directory.\n' >&2
    exit 77
fi
if [[ $(/usr/bin/stat -f %Su "${SOURCE_CERT}") != root ]]; then
    printf 'Cloudflare certificate must be owned by root.\n' >&2
    exit 77
fi
if [[ -n $(/usr/bin/find "${SOURCE_CERT}" -maxdepth 0 \( -perm -020 -o -perm -002 \) -print -quit) ]]; then
    printf 'Cloudflare certificate must not be group/other-writable.\n' >&2
    exit 77
fi
pem_markers=$(/usr/bin/awk '
    /-----BEGIN CERTIFICATE-----/ {begin++}
    /-----END CERTIFICATE-----/ {end++}
    END {printf "%d:%d", begin+0, end+0}
' "${SOURCE_CERT}")
if [[ ${pem_markers} != 1:1 ]]; then
    printf 'Expected exactly one PEM certificate.\n' >&2
    exit 65
fi
actual_sha256=$(/usr/bin/openssl x509 -in "${SOURCE_CERT}" -noout -fingerprint -sha256 |
    /usr/bin/awk -F= 'NF == 2 {print $2}' | /usr/bin/tr -d ':')
if [[ ${actual_sha256} != "${EXPECTED_SHA256}" ]]; then
    printf 'Certificate fingerprint mismatch; refusing to add trust.\n' >&2
    printf 'Expected: %s\nActual:   %s\n' "${EXPECTED_SHA256}" "${actual_sha256}" >&2
    exit 65
fi
cert_subject=$(/usr/bin/openssl x509 -in "${SOURCE_CERT}" -noout -subject)
cert_issuer=$(/usr/bin/openssl x509 -in "${SOURCE_CERT}" -noout -issuer)
subject_dn=${cert_subject#subject=}
issuer_dn=${cert_issuer#issuer=}
if [[ ${subject_dn} != "${issuer_dn}" || ${cert_subject} != *"${EXPECTED_COMMON_NAME}"* ]]; then
    printf 'Certificate is not the expected self-issued Cloudflare Gateway CA.\n' >&2
    exit 65
fi
cert_text=$(/usr/bin/openssl x509 -in "${SOURCE_CERT}" -noout -text)
/usr/bin/grep -F 'CA:TRUE' <<<"${cert_text}" >/dev/null || {
    printf 'Certificate does not assert CA:TRUE.\n' >&2
    exit 65
}
/usr/bin/openssl x509 -in "${SOURCE_CERT}" -checkend 86400 -noout
/usr/bin/openssl verify -CAfile "${SOURCE_CERT}" "${SOURCE_CERT}"
printf 'Pinned Cloudflare CA verified: %s\n' "${EXPECTED_SHA256}"

stage=backup
write_status running "${stage}" 0
stamp=$(/bin/date -u +%Y%m%dT%H%M%SZ)
backup_dir=/var/backups/plntir/${stamp}-cloudflare-gateway-ca
/usr/bin/install -d -o root -g wheel -m 0700 "${backup_dir}"
/usr/bin/install -o root -g wheel -m 0600 "${SOURCE_CERT}" "${backup_dir}/gateway-ca.pem"
{
    printf 'source=%s\n' "${SOURCE_CERT}"
    printf 'sha256=%s\n' "${EXPECTED_SHA256}"
    printf 'common_name=%s\n' "${EXPECTED_COMMON_NAME}"
} >"${backup_dir}/metadata.txt"
/bin/chmod 0600 "${backup_dir}/metadata.txt"
/usr/bin/security dump-trust-settings -d >"${backup_dir}/trust-settings-before.txt" 2>&1 || true
/bin/chmod 0600 "${backup_dir}/trust-settings-before.txt"
if /usr/bin/security trust-settings-export -d "${backup_dir}/trust-settings-before.plist" >/dev/null 2>&1; then
    /bin/chmod 0600 "${backup_dir}/trust-settings-before.plist"
fi
if system_has_pinned_cert; then
    cert_present_before=true
fi

stage=trust-install
write_status running "${stage}" 0
if system_has_pinned_cert && admin_trust_has_expected_ca; then
    printf 'The pinned Cloudflare CA was already trusted for TLS.\n'
else
    /usr/bin/security add-trusted-cert \
        -d -r trustRoot -p ssl -k "${SYSTEM_KEYCHAIN}" "${SOURCE_CERT}"
    trust_changed=true
fi

stage=trust-verification
write_status running "${stage}" 0
system_has_pinned_cert || {
    printf 'Pinned certificate was not found in the System keychain after installation.\n' >&2
    exit 70
}
admin_trust_has_expected_ca || {
    printf 'The Cloudflare CA is missing from the admin trust settings after installation.\n' >&2
    exit 70
}
/usr/bin/security dump-trust-settings -d >"${backup_dir}/trust-settings-after.txt" 2>&1
/bin/chmod 0600 "${backup_dir}/trust-settings-after.txt"
trusted=true
printf 'System keychain TLS trust verified for %s.\n' "${EXPECTED_COMMON_NAME}"
printf 'Rollback evidence: %s\n' "${backup_dir}"

stage=tls-probe
write_status running "${stage}" 0
set +e
/usr/bin/curl -sS -v --connect-timeout 15 --max-time 30 -o /dev/null \
    https://example.com >"${TLS_FILE}" 2>&1
tls_rc=$?
set -e
/bin/chmod 0644 "${TLS_FILE}"
if /usr/bin/grep -F "${EXPECTED_COMMON_NAME}" "${TLS_FILE}" >/dev/null; then
    inspection_observed=true
fi
if [[ ${tls_rc} -eq 0 ]]; then
    printf 'HTTPS probe succeeded.\n'
else
    printf 'Warning: HTTPS probe failed (curl rc=%d); trust itself was verified locally.\n' "${tls_rc}" >&2
fi
if [[ ${inspection_observed} == true ]]; then
    printf 'Cloudflare Gateway TLS inspection was observed in the live certificate chain.\n'
else
    printf 'Gateway CA trust is ready; live TLS inspection was not observed yet.\n'
    printf 'Enable the Cloudflare Gateway TLS-decryption setting, then rerun the probe.\n'
fi

finished=true
